name: planner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.18.1
  sqflite: ^2.2.0
  path: ^1.8.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/calendar.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "assets/icon/calendar.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/icon/calendar.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/icon/calendar.png"